name: Despliegue Backend Encuestas Unistmo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Despliegue Backend Producción - Encuestas Unistmo
    runs-on: ubuntu-latest
    steps:
      - name: 1- Checkout del repositorio
        uses: actions/checkout@v3

      - name: 2- Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SV_IP }}
          username: ${{ secrets.SV_USER }}
          password: ${{ secrets.SV_PASSWORD }}
          script: |
            cd /var/www/encuestas/back-encuestas-unistmo

            git checkout main
            git pull origin main

            docker compose down
            docker compose build --no-cache
            docker compose up -d
